version: 2

sources:
    - name: bigquery_data
      description: "Raw data sources for NYC taxi rides"
      database: modulo4-487315 # project ID
      schema: taxi_trips_data_all # Dataset name
      tables:
        - name: green_tripdata
          description: Raw green trip data for NYC taxi rides
          columns:
            - name: provider_code
              description: |
                A code indicating the provider associated with the trip record.
                1: "Creative Mobile Technologies, LLC"
                2: "VeriFone Inc."
                3: "Uber Technologies Inc."
              data_type: integer
          meta:
            pii: false
            ownership: data_team
            importance: high
            formatting: none
        - name: yellow_tripdata
          description: "Raw yellow trip data for NYC taxi rides"
          meta:
            pii: false
            ownership: data_team
            importance: high
            formatting: none
