# 1. IDENTIFICACIÓN DEL PROYECTO
# 'name' es el nombre único de tu proyecto. 
# Importante: Todo lo que definas en la sección 'models' al final debe colgar de este nombre.
name: 'taxi_rides_ny'
version: '1.0.0'
config-version: 2

# 2. CONEXIÓN CON LA NUBE (dbt Cloud CLI)
# Este bloque le dice al comando dbt de tu terminal que no use una base de datos local,
# sino que mande la ejecución a tu proyecto específico en la plataforma de dbt Cloud.
dbt-cloud:
  project-id: 70471823554289

# 'profile' indica qué configuración de conexión usar. 
# En dbt Cloud, siempre se deja como 'default' porque la conexión se configura en la interfaz web.
profile: 'default'

# 3. RUTAS DE DIRECTORIOS
# Aquí le dices a dbt en qué carpetas de tu VS Code están guardados los archivos.
model-paths: ["models"]      # Donde están tus archivos .sql (los modelos)
analysis-paths: ["analyses"] # Consultas SQL que no son modelos (para análisis rápido)
test-paths: ["tests"]        # Pruebas de calidad de datos (asegurar que no haya nulos, etc.)
seed-paths: ["seeds"]        # Archivos CSV pequeños que quieres cargar como tablas
macro-paths: ["macros"]      # Funciones reutilizables de Jinja (como pedazos de código SQL)
snapshot-paths: ["snapshots"] # Para llevar historial de cambios en tablas (Slowly Changing Dimensions)

# 4. ARCHIVOS TEMPORALES
# 'target-path' es donde dbt guarda el SQL final compilado después de procesar el Jinja.
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages" # Carpetas que se borran cuando corres 'dbt clean'

# 5. CONFIGURACIÓN DE MODELOS (Cómo se crean en la base de datos)
# Aquí defines las reglas para tus carpetas.
models:
  taxi_rides_ny: # <-- Este nombre DEBE coincidir con el 'name' de la línea 4
    
    # Configuración para la carpeta 'models/staging/'
    staging:
      +materialized: view # Los modelos aquí se crearán como VISTAS (más rápido, menos espacio)
    
    # Configuración para la carpeta 'models/core/'
    core:
      +materialized: table # Los modelos aquí se crearán como TABLAS físicas (mejor rendimiento para dashboards)
